### ISSUE TITLE
Latest release 0.20 fails installation on CentOS 7

### ISSUE THREAD

**Issue by provector** [majensen/perlbolt#43]
As in description Im trying to install the 0.20 with cpanminus. I have resolved all the dependencies and installed latest version on Neo4j::Client. Log fails with following:

```
cpanm (App::cpanminus) 1.6922 on perl 5.016003 built for x86_64-linux-thread-multi
Work directory is /root/.cpanm/work/1630670993.12612
You have make /bin/make
You have LWP 6.56
You have /bin/tar: tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /bin/unzip
Checking if you have ExtUtils::MakeMaker 6.31 ... Yes (7.62)
Checking if you have ExtUtils::Install 1.46 ... Yes (2.06)
--> Working on Neo4j-Bolt-0.20.tar.gz
Fetching file:///home/mpiekarski/GNIPerf/Neo4j-Bolt-0.20.tar.gz
-> OK
Unpacking Neo4j-Bolt-0.20.tar.gz
Entering Neo4j-Bolt-0.20
Checking configure dependencies from META.json
Checking if you have Try::Tiny 0 ... Yes (0.30)
Checking if you have ExtUtils::CChecker 0 ... Yes (0.11)
Checking if you have Module::Build 0.36_14 ... Yes (0.4231)
Checking if you have Neo4j::Client 0.17 ... Yes (0.46)
Checking if you have Module::Build 0.36 ... Yes (0.4231)
Configuring Neo4j-Bolt-0.20
Running Build.PL
Undefined subroutine &Neo4j::Client::LIBS_ARY called at Build.PL line 69.
-> N/A
-> FAIL Configure failed for Neo4j-Bolt-0.20. See /root/.cpanm/work/1630670993.12612/build.log for details.
```

Any assistance would be welcome.

**Comment by provector** [comment]
I tried it on a different system, after resolving dependecies I get that error:

```
Appending installation info to /root/perl5/lib/perl5/x86_64-linux-thread-multi/perllocal.pod
  AJNN/Neo4j-Driver-0.27.tar.gz
  /bin/make install  -- OK
[root@den02vmfedpvcl02 tmp]# cpanm Neo4j-Bolt-0.20.tar.gz
--> Working on Neo4j-Bolt-0.20.tar.gz
Fetching file:///opt/assure1/tmp/Neo4j-Bolt-0.20.tar.gz ... OK
==> Found dependencies: Neo4j::Client
--> Working on Neo4j::Client
Fetching http://www.cpan.org/authors/id/M/MA/MAJENSEN/Neo4j-Client-0.46.tar.gz ... OK
Configuring Neo4j-Client-0.46 ... OK
==> Found dependencies: tool::AM
! Finding tool::AM on cpanmetadb failed.
! Finding tool::AM (0) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution tool::AM (0)
! Installing the dependencies failed: Module 'tool::AM' is not installed
! Bailing out the installation for Neo4j-Client-0.46.
! Installing the dependencies failed: Module 'Neo4j::Client' is not installed
! Bailing out the installation for Neo4j-Bolt-0.20.
[root@den02vmfedpvcl02 tmp]# cpan tool::AM
Reading '/root/.cpan/Metadata'
  Database was generated on Fri, 03 Sep 2021 07:29:03 GMT
Warning: Cannot install tool::AM, don't know what it is.
Try the command

    i /tool::AM/

to find objects with matching identifiers.
[root@den02vmfedpvcl02 tmp]#
```

**Comment by johannessen** [comment]
Hi @provector, thanks for getting in touch. The latest release is currently [0.4201](https://metacpan.org/release/MAJENSEN/Neo4j-Bolt-0.4201). Neo4j::Bolt and Neo4j::Client are pretty tightly coupled, so if you choose to use an older release of the one, you should probably use an older release of the other as well. Try [Neo4j::Bolt 0.20](https://metacpan.org/release/MAJENSEN/Neo4j-Bolt-0.20) with [Neo4j::Client version 0.17](https://metacpan.org/release/MAJENSEN/Neo4j-Client-0.17).

Those older versions won’t work with Neo4j 4 though. We’re hoping to fix Neo4j::Bolt support for older Perl versions in the future. In the meantime, if you need Neo4j 4, you may have to either upgrade your Perl to at least v5.18 or use HTTP via [Neo4j::Driver](https://metacpan.org/pod/Neo4j::Driver).

For the second problem you mention, it is perhaps best to open a new issue in the [majensen/neoclient](https://github.com/majensen/neoclient) repository rather than discussing it here.

**Comment by provector** [comment]
Thank you for the prompt reply! I wasn't aware latest release is 0.4201, I will try installing the newer version so!

As for the second issue thanks, Ill post it there.

**Comment by majensen** [comment]
@provector @johannessen thanks for this. Agree we need to tighten up the releases. Sorry for this inconvenience!

**Comment by johannessen** [comment]
Closing this, as it seems the issue was addressed. Thanks again!
