### ISSUE TITLE
Fix automated tests / CI

### ISSUE THREAD

**Issue by johannessen** [majensen/perlbolt#47]
It’d be nice to have the build tests working again, and run them on a bunch of different Perl versions. Could probably be done similarly to the driver’s new GH Action.

Feel free to assign this to me if you like.

**Comment by majensen** [comment]
Hey @johannessen - With the new development, I think it's def time to get CI going again. Agree w/using Actions. If you have interest, go for it - but I will prob work on it once we pull in feat-v5.0.

**Comment by johannessen** [comment]
Okay, so I basically just did copy & paste from the Neo4j::Driver repository here.

The first job builds the distribution, the second job installs it on a number of different Perl/Neo4j combos. The result isn’t great because the bottlenecks of the two projects are in different locations: For my driver, the slowest part is building the distribution with Dist::Zilla, but for perlbolt, installation of the dependencies seems to be slowest. So you would need to cache those, which I didn’t for the driver. As a result, this new workflow is really really slow.

I’m not at all happy with this solution. That said, it *does* work, so I suppose it’s a lot better than it was.

Perhaps it should be redone from scratch, but I’m not sure how much time would be justified being spent on that. Closing this issue for now, but feel free to reopen.

**Comment by johannessen** [comment]
Oh, and the [cpanfile](https://github.com/majensen/perlbolt/blob/76d50ab80e43c6fb75c02a7f92a3bc8a2a319465/cpanfile) is currently only used by the GH workflow. I didn’t need that for the driver because Dist::Zilla determines prerequisites automatically.

Should you wish to remove the redundancies from [Makefile.PL](https://github.com/majensen/perlbolt/blob/76d50ab80e43c6fb75c02a7f92a3bc8a2a319465/Makefile.PL), you could use [ExtUtils::MakeMaker::CPANfile](https://metacpan.org/pod/ExtUtils::MakeMaker::CPANfile).

**Comment by majensen** [comment]
Arne - this is great. Obviously my $job has sucked away all my time. I will get back to this, but in the meantime do what makes it work to your satisfaction.Sent from my iPhoneOn Jul 27, 2023, at 5:46 AM, Arne Johannessen ***@***.***> wrote:﻿
Oh, and the cpanfile is currently only used by the GH workflow. I didn’t need that for the driver because Dist::Zilla determines prerequisites automatically.
Should you wish to remove the redundancies from Makefile.PL, you could use ExtUtils::MakeMaker::CPANfile.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/majensen/perlbolt/issues/47#issuecomment-1653273645",
"url": "https://github.com/majensen/perlbolt/issues/47#issuecomment-1653273645",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]-- 
This message has been scanned for viruses and
dangerous content by
MailScanner, and is
believed to be clean.


-- 
This message has been scanned for viruses and
dangerous content by
MailScanner, and is
believed to be clean.

**Comment by johannessen** [comment]
No worries, Mark – I think I am satisfied with that Actions workflow, just as long as I don’t have to look at it again. 😄
