### ISSUE TITLE
Implement element ID (Bolt v5)

### ISSUE THREAD

**Issue by johannessen** [majensen/perlbolt#50]
Neo4j 5 introduced Bolt version 5.0, which expands node and relationship structures with a new element ID string. The latter is meant to replace the numeric ID. I expect adding these to perlbolt would be relatively easy, although it would require changes to [libneo4j-client](https://github.com/majensen/libneo4j-client) for the [new structure semantics](https://github.com/neo4j/docs-bolt/blob/main/modules/ROOT/pages/bolt/structure-semantics.adoc), in addition to `neo4j_node_to_HV()` and `neo4j_relationship_to_HV()` here in [CTypeHandlers.xs](https://github.com/majensen/perlbolt/blob/master/lib/Neo4j/Bolt/CTypeHandlers.xs).

However, I think there have been some additional changes to Bolt since version 4.0. Perhaps only minor ones – I haven’t followed things too closely. The documentation site ~7687.org is down at present~ _has moved to [neo4j.com/docs/bolt/](https://neo4j.com/docs/bolt/current/bolt/)_. Its source is available on GH in [@neo4j/docs-bolt](https://github.com/neo4j/docs-bolt/tree/main/modules/ROOT/pages) and has received several updates throughout 2022, so hopefully it’s complete.

Once element IDs are provided by Neo4j::Bolt, the behaviour of the driver will be more consistent between Bolt and HTTP, see ["element_id" in Neo4j::Driver::Type::Relationship](https://metacpan.org/pod/Neo4j::Driver::Type::Relationship#METHODS).

**Comment by majensen** [comment]
This will be worth implementing @johannessen - I'm also needing to have a look at majensen/libneo4j-client to see how the ID handling will have to change in the type structures there. Could be a while before I get to that (but I am interested).

**Comment by johannessen** [comment]
I’d favour a data structure with space for both `element_id` and `id`. That would save me from having to guess what the correct value of `id` might be.

**Comment by majensen** [comment]
Working on this in libneo4j-client fork now

**Comment by majensen** [comment]
@johannessen [this tag](https://github.com/majensen/libneo4j-client/releases/tag/v5.0.0-maj-beta) on majensen/libneo4j-client adds element_id and preserves the id field. Next step is to update majensen/neoclient with the library updates, then add the appropriate accessors and types here, I believe.

**Comment by majensen** [comment]
Have a try of https://github.com/majensen/perlbolt/tree/v0.5000rc (in feat-v5.0) for element ids in Nodes and Relationships. The new libneo4j-client will create an element id (just the stringified integer id) for  pre-5.0 servers, so this field should always be present. (Note that v0.5000 requires Neo4j::Client 0.51 based on the latest libneo4j-client. N:C 0.51 is in CPAN.)

**Comment by majensen** [comment]
Yeah - it was much easier to populate elt id (in neoclient) with something rather than have two different  versions of the structure - but if you want the Perl logic can undef that based on version. I think the elt id == id is a bit "undocumented"Sent from my iPhoneOn Apr 20, 2023, at 9:26 AM, Arne Johannessen ***@***.***> wrote:﻿
Awesome progress! Unfortunately, I’m very strapped for time at the moment. I did skim through the code changes here; looks good to me so far. Will look into this properly as soon as I can, but it’ll take a while.
I kind of expected the element id to be undef for pre-5.0, but now I could probably use $element_id eq $id to determine whether the Neo4j server supports element IDs, right?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/majensen/perlbolt/issues/50#issuecomment-1516328800",
"url": "https://github.com/majensen/perlbolt/issues/50#issuecomment-1516328800",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]-- 
This message has been scanned for viruses and
dangerous content by
MailScanner, and is
believed to be clean.


-- 
This message has been scanned for viruses and
dangerous content by
MailScanner, and is
believed to be clean.

**Comment by johannessen** [comment]
> Yeah - it was much easier to populate elt id (in neoclient) with something rather than have two different  versions of the structure - but if you want the Perl logic can undef that based on version. I think the elt id == id is a bit "undocumented"

I imagine the XS logic should automatically translate a C null pointer to Perl `undef`, but have admittedly never tried it.

Yes, instead of the equality check, I would indeed prefer one of the following ways to mark a missing element ID:
* element ID field is `undef`
* element ID field is an empty string
* an additional flag in the hash
